/**
 * @description all const type of transactions page
 */
export const RESET_ALL = 'TRANSACTIONS/RESET';

export const GET_ALL_TRANSACTIONS = 'TRANSACTIONS/GET_ALL_TRANSACTIONS';
export const GET_ALL_TRANSACTIONS_SUCCESS = 'TRANSACTIONS/GET_ALL_TRANSACTIONS_SUCCESS';
export const GET_ALL_TRANSACTIONS_FAILED = 'TRANSACTIONS/GET_ALL_TRANSACTIONS_FAILED';
