/**
 * @description all const type of with draw page
 */
export const RESET_ALL = 'WITH_DRAW/RESET';

export const GET_ALL_WITH_DRAW = 'WITH_DRAW/GET_ALL_WITH_DRAW';
export const GET_ALL_WITH_DRAW_SUCCESS = 'WITH_DRAW/GET_ALL_WITH_DRAW_SUCCESS';
export const GET_ALL_WITH_DRAW_FAILED = 'WITH_DRAW/GET_ALL_WITH_DRAW_FAILED';

export const CHANGE_STATUS = 'WITH_DRAW/CHANGE_STATUS';
export const CHANGE_STATUS_SUCCESS = 'WITH_DRAW/CHANGE_STATUS_SUCCESS';
export const CHANGE_STATUS_FAILED = 'WITH_DRAW/CHANGE_STATUS_FAILED';