const actions = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_CLEANUP: 'LOGIN_CLEANUP',
  GET_USER_ROLE: 'GET_USER_ROLE',
  GET_USER_ROLE_SUCCESS: 'GET_USER_ROLE_SUCCESS',
};

export default actions;
