/**
 * @description all const type of wallet page
 */
export const RESET_ALL = 'USER_WALLETS/RESET';

export const GET_ALL_USER_WALLETS = 'USER_WALLETS/GET_ALL_USER_WALLETS';
export const GET_ALL_USER_WALLETS_SUCCESS = 'USER_WALLETS/GET_ALL_USER_WALLETS_SUCCESS';
export const GET_ALL_USER_WALLETS_FAILED = 'USER_WALLETS/GET_ALL_USER_WALLETS_FAILED';
