const actions = {
  FACEBOOK_LOGIN_REQUEST: 'FACEBOOK_LOGIN_REQUEST',
  FACEBOOK_LOGIN_SUCCESS: 'FACEBOOK_LOGIN_SUCCESS',
  FACEBOOK_LOGIN_FAILURE: 'FACEBOOK_LOGIN_FAILURE',
  FACEBOOK_LOGIN_CLEANUP: 'FACEBOOK_LOGIN_CLEANUP',
};

export default actions;
