/**
 * @description all const type of room category page
 */
export const RESET_ALL = 'ROOM_CATEGORY/RESET';

export const GET_ALL_ROOM_CATEGORY = 'ROOM_CATEGORY/GET_ALL_ROOM_CATEGORY';
export const GET_ALL_ROOM_CATEGORY_SUCCESS = 'ROOM_CATEGORY/GET_ALL_ROOM_CATEGORY_SUCCESS';
export const GET_ALL_ROOM_CATEGORY_FAILED = 'ROOM_CATEGORY/GET_ALL_ROOM_CATEGORY_FAILED';

export const CREATE_ROOM_CATEGORY = 'ROOM_CATEGORY/CREATE_ROOM_CATEGORY';
export const CREATE_ROOM_CATEGORY_SUCCESS = 'ROOM_CATEGORY/CREATE_ROOM_CATEGORY_SUCCESS';
export const CREATE_ROOM_CATEGORY_FAILED = 'ROOM_CATEGORY/CREATE_ROOM_CATEGORY_FAILED';

export const DELETE_ROOM_CATEGORY = 'ROOM_CATEGORY/DELETE_ROOM_CATEGORY';
export const DELETE_ROOM_CATEGORY_SUCCESS = 'ROOM_CATEGORY/DELETE_ROOM_CATEGORY_SUCCESS';
export const DELETE_ROOM_CATEGORY_FAILED = 'ROOM_CATEGORY/DELETE_ROOM_CATEGORY_FAILED';

export const MODIFY_ROOM_CATEGORY = 'ROOM_CATEGORY/MODIFY_ROOM_CATEGORY';
export const MODIFY_ROOM_CATEGORY_SUCCESS = 'ROOM_CATEGORY/MODIFY_ROOM_CATEGORY_SUCCESS';
export const MODIFY_ROOM_CATEGORY_FAILED = 'ROOM_CATEGORY/MODIFY_ROOM_CATEGORY_FAILED';
