export const language = {
  no: 'No.',
  username: 'Full name',
  status: 'Status',
  type: 'Type',
  amount: 'Amount',
  currencyUnit: 'Currency unit',
  updatedAt: 'Updated at',
  createdAt: 'Created at',
  deposit: 'Deposit',
  withDraw: 'With draw',
  convert: 'Convert',
  buyGift: 'Buy gift',
  receiveGift: 'Receive gift',
  gameReward: 'Game reward',
  gameDeposit: 'Game deposit',
  pending: 'Pending',
  approved: 'Approved',
  success: 'Success',
  rejected: 'Rejected',
  failed: 'Failed',
  cancelled: 'Cancelled',
  day: 'day',
  week: 'week',
  month: 'month',
  dateRange: 'Please select date range',
  reason: 'Reason',
  bannedUntil: 'Banned until',
  balance: 'Balance',
  diamond_commission: 'Diamond Commission',
  diamond: 'Diamond',
  gold: 'Gold',
};
