/**
 * @description all const type of room page
 */
export const RESET_ALL = 'BANNER/RESET';

export const GET_ALL_BANNERS = 'BANNER/GET_ALL_BANNERS';
export const GET_ALL_BANNERS_SUCCESS = 'BANNER/GET_ALL_BANNERS_SUCCESS';
export const GET_ALL_BANNERS_FAILED = 'BANNER/GET_ALL_BANNERS_FAILED';

export const DELETE_BANNER = 'BANNER/DELETE_BANNER';
export const DELETE_BANNER_SUCCESS = 'BANNER/DELETE_BANNER_SUCCESS';
export const DELETE_BANNER_FAILED = 'BANNER/DELETE_BANNER_FAILED';

export const MODIFY_BANNER = 'BANNER/MODIFY_BANNER';
export const MODIFY_BANNER_SUCCESS = 'BANNER/MODIFY_BANNER_SUCCESS';
export const MODIFY_BANNER_FAILED = 'BANNER/MODIFY_BANNER_FAILED';

export const CREATE_BANNER = 'BANNER/CREATE_BANNER';
export const CREATE_BANNER_SUCCESS = 'BANNER/CREATE_BANNER_SUCCESS';
export const CREATE_BANNER_FAILED = 'BANNER/CREATE_BANNER_FAILED';
