const actions = {
  CHANGE_STATUS: {
    CHANGE_IDOL_STATUS_REQUEST: 'CHANGE_IDOL_STATUS_REQUEST',
    CHANGE_IDOL_STATUS_SUCCESS: 'CHANGE_IDOL_STATUS_SUCCESS',
    CHANGE_IDOL_STATUS_FAILURE: 'CHANGE_IDOL_STATUS_FAILURE',
    CHANGE_IDOL_STATUS_CLEANUP: 'CHANGE_IDOL_STATUS_CLEANUP',
  },
};

export default actions;
