const actions = {
  FETCH: {
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FETCH_USERS_CLEANUP: 'FETCH_USERS_CLEANUP',
  },
  UPDATE: {
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    UPDATE_USER_CLEANUP: 'UPDATE_USER_CLEANUP',
  },
  DELETE: {
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
    DELETE_USER_CLEANUP: 'DELETE_USER_CLEANUP',
  },
  SEARCH: {
    SEARCH_USER_REQUEST: 'SEARCH_USER_REQUEST',
    SEARCH_USER_SUCCESS: 'SEARCH_USER_SUCCESS',
    SEARCH_USER_FAILURE: 'SEARCH_USER_FAILURE',
    SEARCH_USER_CLEANUP: 'SEARCH_USER_CLEANUP',
  },
};

export default actions;
