/**
 * @description all const type of room page
 */
export const RESET_ALL = 'ROOMS/RESET';

export const GET_ALL_ROOMS = 'ROOMS/GET_ALL_ROOMS';
export const GET_ALL_ROOMS_SUCCESS = 'ROOMS/GET_ALL_ROOMS_SUCCESS';
export const GET_ALL_ROOMS_FAILED = 'ROOMS/GET_ALL_ROOMS_FAILED';

export const DELETE_ROOM = 'ROOMS/DELETE_ROOM';
export const DELETE_ROOM_SUCCESS = 'ROOMS/DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAILED = 'ROOMS/DELETE_ROOM_FAILED';

export const MODIFY_ROOM = 'ROOMS/MODIFY_ROOM';
export const MODIFY_ROOM_SUCCESS = 'ROOMS/MODIFY_ROOM_SUCCESS';
export const MODIFY_ROOM_FAILED = 'ROOMS/MODIFY_ROOM_FAILED';

export const GET_ALL_ROOM_CATEGORY = 'ROOMS/GET_ALL_ROOM_CATEGORY';
export const GET_ALL_ROOM_CATEGORY_SUCCESS = 'ROOMS/GET_ALL_ROOM_CATEGORY_SUCCESS';
export const GET_ALL_ROOM_CATEGORY_FAILED = 'ROOMS/GET_ALL_ROOM_CATEGORY_FAILED';
