const actions = {
  FETCH: {
    FETCH_GIFTS_REQUEST: 'FETCH_GIFTS_REQUEST',
    FETCH_GIFTS_SUCCESS: 'FETCH_GIFTS_SUCCESS',
    FETCH_GIFTS_FAILURE: 'FETCH_GIFTS_FAILURE',
    FETCH_GIFTS_CLEANUP: 'FETCH_GIFTS_CLEANUP',
  },

  GET: {
    GET_GIFT_REQUEST: 'GET_GIFT_REQUEST',
    GET_GIFT_SUCCESS: 'GET_GIFT_SUCCESS',
    GET_GIFT_FAILURE: 'GET_GIFT_FAILURE',
    GET_GIFT_CLEANUP: 'GET_GIFT_CLEANUP',
  },

  CREATE: {
    CREATE_GIFT_REQUEST: 'CREATE_GIFT_REQUEST',
    CREATE_GIFT_SUCCESS: 'CREATE_GIFT_SUCCESS',
    CREATE_GIFT_FAILURE: 'CREATE_GIFT_FAILURE',
    CREATE_GIFT_CLEANUP: 'CREATE_GIFT_CLEANUP',
  },

  UPDATE: {
    UPDATE_GIFT_REQUEST: 'UPDATE_GIFT_REQUEST',
    UPDATE_GIFT_SUCCESS: 'UPDATE_GIFT_SUCCESS',
    UPDATE_GIFT_FAILURE: 'UPDATE_GIFT_FAILURE',
    UPDATE_GIFT_CLEANUP: 'UPDATE_GIFT_CLEANUP',
  },

  DELETE: {
    DELETE_GIFT_REQUEST: 'DELETE_GIFT_REQUEST',
    DELETE_GIFT_SUCCESS: 'DELETE_GIFT_SUCCESS',
    DELETE_GIFT_FAILURE: 'DELETE_GIFT_FAILURE',
    DELETE_GIFT_CLEANUP: 'DELETE_GIFT_CLEANUP',
  },
};

export default actions;
